import Link from "next/link";
import { SiteNav } from "../site-nav";
export const metadata = { title: "Get the extension — NaraNews" };
export default function InstallPage() {
  const configuredUrl = process.env.CHROME_WEB_STORE_URL;
  let storeUrl: string | null = null;
  try { const url = new URL(configuredUrl ?? ""); if (url.protocol === "https:" && url.hostname === "chromewebstore.google.com") storeUrl = url.href; } catch { /* Show local instructions until published. */ }
  return <><SiteNav /><main className="container app-content prose"><p className="eyebrow">NARANEWS FOR CHROME</p><h1>Get your digest in Chrome</h1>{storeUrl ? <a className="primary-button" href={storeUrl} target="_blank" rel="noopener noreferrer">Open Chrome Web Store ↗</a> : <><p>The Chrome Web Store installation link isn’t available yet. You can use the live web digest now, or install the development extension from the project source.</p><a className="text-link" href="https://github.com/Khant-Nyar-Ko-Ko/nara" target="_blank" rel="noopener noreferrer">Open the project source ↗</a><h2>Local development installation</h2><ol><li>Download or clone the project and run <code>npm install</code> in its root folder.</li><li>Configure the backend using <code>web/.env.example</code>, then run <code>npm run dev --workspace=web</code>.</li><li>Run <code>npm run build --workspace=extension</code>.</li><li>In Chrome, open <code>chrome://extensions</code>, enable Developer mode, choose <strong>Load unpacked</strong>, and select <code>extension/dist</code>.</li><li>Pin NaraNews, open the popup, and choose your topics.</li></ol><p>The development build connects to <code>http://localhost:3000</code>. Keep the backend running. A hosted backend must also be configured in the extension’s API URL and host permissions.</p></>}<h2>Connect email delivery</h2><p>Open Settings from the extension and verify the same email address you use on this website. Your email consent belongs to that account, but the extension needs its own sign-in to request delivery while Chrome is idle.</p><div className="page-actions"><Link className="primary-button" href="/digest">Read the live digest</Link><Link className="text-link" href="/settings">Manage email delivery →</Link></div></main></>;
}
